name: Release to PyPI

on:
  push:
    tags:
      - "v*.*.*"  # Triggers on tags like v0.1.0

jobs:
  release:
    runs-on: ubuntu-latest  # Builds on Linux for clean PyPI packages

    steps:
    - uses: actions/checkout@v4

    - name: Set up uv
      uses: astral-sh/setup-uv@v3
      with:
        version: latest

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"  # Use a recent version for building

    - name: Install dependencies
      run: uv sync --all-extras --dev

    - name: Build package
      run: uv build

    - name: Publish to PyPI
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}  # Add this secret in GitHub repo settings
      run: uv publish --token $PYPI_TOKEN
